### PR TITLE
rename config_shorewall to shorewall_config to have a clear namespace

### PR DESCRIPTION
**Pull request by EugenMayer**

### CODE REVIEW

**Comment by mrlesmithjr** [comment]
@EugenMayer Personally I prefer to keep vars named as config_xxxx as I use this method in all of my roles. Do you see any reason why this is not a good idea? I am open but just a preference.

**Comment by EugenMayer** [comment]
You are  aware that this is a global namespace..right? No matter what you prefer, you are cluttering the global namespace

**Comment by mrlesmithjr** [comment]
@EugenMayer Absolutely I am fully aware of that.

**Comment by EugenMayer** [comment]
whatever. I am not going to use this role anyway, so you can close this PR or whatever, no issues with it.

**Comment by mrlesmithjr** [comment]
You obviously took the time to submit a PR for this so it must have been important to you. And I did not state that is was my preference and it could not be changed. I was actually looking for a meaningful reason instead of whatever. I do actually like your proposal as I had just been in the habit of using config_xxxx. If you are going to use the role or not, does not mean it is not a valuable contribution for others.

**Comment by EugenMayer** [comment]
@mrlesmithjr i am not using this role not because of the role itself, rather i ditched ansible again, so i  will not contribute anylonger. So just do not play attention to my POV and do what ever you like. 

My POV: anything as a variable name, which does not prefix your role name, is extremly wrong. But thats IMHO

**Comment by mrlesmithjr** [comment]
@EugenMayer PR has been merged. Thanks for your contribution!

**Comment by mrlesmithjr** [comment]
@EugenMayer No worries man.

**Pull request merged**
