### PR TITLE
Multiples masquerade rules

### PR DESCRIPTION
**Pull request by chris968**
Add the ability to generate multiples masquerade rules

### CODE REVIEW

**Comment by mrlesmithjr** [comment]
@chris968 I'll take a look into this soon. There appears to be some CI tests that are failing above you may want to look into.

**Comment by chris968** [comment]
I've solve the issues, just some trailing-spaces.

**Comment by mrlesmithjr** [comment]
excellent, will be merging here in a few.

**Comment by mrlesmithjr** [comment]
@chris968 Merged. Thanks for this.

**Pull request merged**
